version: "3.8"

services:
    spy_listener:                    
        build:
            context: ./wormbole/spy_listener
            dockerfile: Dockerfile
        ports:
        - "8000:8000"
        container_name: spy_listener
        env_file: 
        - .env
        depends_on:
        - db   

    ci:
        container_name: spy_listener_ci
        image: "ax_protocol/spy_listener"
        env_file:
            - tests.env
        entrypoint: app/ci/initiate_tests.sh
        depends_on:
            - test_db

    test_db:
        image: library/postgres:12-alpine
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5444
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=spy_listener_dev_test
        ports:
            - 5444:5444
        command: -p 5444

    db:
        image: library/postgres:12-alpine
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=spy_listener_dev
        ports:
            - 5432:5432