version: "3.8"

services:
    spy_listener:
        build:
            context: ./wormhole/spy_listener
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        container_name: spy_listener
        env_file:
            - .env
        depends_on:
            - db

    relayer:
        build:
            context: ./wormhole/relayer
            dockerfile: Dockerfile
        ports:
            - "9000:9000"
        container_name: relayer
        env_file:
            - .env
        depends_on:
            - db

    db:
        image: library/postgres:12-alpine
        container_name: ax_database
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5432
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ax_relayer_dev
        ports:
            - 5432:5432

    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq_broker
        ports:
            - 5672:5672
            - 15672:15672
        env_file:
            - .env

    ci:
        container_name: spy_listener_ci
        image: "ax_protocol/spy_listener"
        env_file:
            - tests.env
        entrypoint: app/ci/initiate_tests.sh
        depends_on:
            - test_db

    test_db:
        image: library/postgres:12-alpine
        container_name: test_ax_database
        environment:
            - POSTGRES_HOST=db
            - POSTGRES_PORT=5444
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ax_relayer_dev_test
        ports:
            - 5444:5444
        command: -p 5444

    test_rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: test_rabbitmq_broker
        ports:
            - 5673:5673
            - 15673:15673
        env_file:
            - tests.env
