version: "3.8"

services:
  # ****************************************************************************
  #
  #  Main Containers
  #
  # ****************************************************************************
  spy_listener:
    build:
      context: ./wormhole/spy_listener
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: spy_listener
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq  
  
  db:
      image: library/postgres:12-alpine
      container_name: ax_database
      environment:
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=ax_relayer_dev
      ports:
        - 5432:5432

  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq_broker
      ports:
        - 5672:5672
        - 15672:15672  
  # ****************************************************************************
  #
  #  Testing Containers
  #
  # ****************************************************************************  
  test_db:
    image: library/postgres:12-alpine
    container_name: test_ax_database
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5444
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ax_relayer_dev_test
    ports:
      - 5444:5444
    command: -p 5444