# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spy/v1/spy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.infrastructure.clients.streams.grpc.google.api import (
    annotations_pb2 as google_dot_api_dot_annotations__pb2,
)
from app.infrastructure.clients.streams.grpc.gossip.v1 import (
    gossip_pb2 as gossip_dot_v1_dot_gossip__pb2,
)
from app.infrastructure.clients.streams.grpc.publicrpc.v1 import (
    publicrpc_pb2 as publicrpc_dot_v1_dot_publicrpc__pb2,
)

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10spy/v1/spy.proto\x12\x06spy.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x16gossip/v1/gossip.proto\x1a\x1cpublicrpc/v1/publicrpc.proto"Q\n\rEmitterFilter\x12\'\n\x08\x63hain_id\x18\x01 \x01(\x0e\x32\x15.publicrpc.v1.ChainID\x12\x17\n\x0f\x65mitter_address\x18\x02 \x01(\t"T\n\x0b\x42\x61tchFilter\x12\'\n\x08\x63hain_id\x18\x01 \x01(\x0e\x32\x15.publicrpc.v1.ChainID\x12\r\n\x05tx_id\x18\x02 \x01(\x0c\x12\r\n\x05nonce\x18\x03 \x01(\r"P\n\x16\x42\x61tchTransactionFilter\x12\'\n\x08\x63hain_id\x18\x01 \x01(\x0e\x32\x15.publicrpc.v1.ChainID\x12\r\n\x05tx_id\x18\x02 \x01(\x0c"\xb9\x01\n\x0b\x46ilterEntry\x12/\n\x0e\x65mitter_filter\x18\x01 \x01(\x0b\x32\x15.spy.v1.EmitterFilterH\x00\x12+\n\x0c\x62\x61tch_filter\x18\x02 \x01(\x0b\x32\x13.spy.v1.BatchFilterH\x00\x12\x42\n\x18\x62\x61tch_transaction_filter\x18\x03 \x01(\x0b\x32\x1e.spy.v1.BatchTransactionFilterH\x00\x42\x08\n\x06\x66ilter"A\n\x19SubscribeSignedVAARequest\x12$\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\x13.spy.v1.FilterEntry"G\n\x1fSubscribeSignedVAAByTypeRequest\x12$\n\x07\x66ilters\x18\x01 \x03(\x0b\x32\x13.spy.v1.FilterEntry"/\n\x1aSubscribeSignedVAAResponse\x12\x11\n\tvaa_bytes\x18\x01 \x01(\x0c"\xa5\x01\n SubscribeSignedVAAByTypeResponse\x12\x34\n\nsigned_vaa\x18\x01 \x01(\x0b\x32\x1e.gossip.v1.SignedVAAWithQuorumH\x00\x12?\n\x10signed_batch_vaa\x18\x02 \x01(\x0b\x32#.gossip.v1.SignedBatchVAAWithQuorumH\x00\x42\n\n\x08vaa_type2\xb3\x02\n\rSpyRPCService\x12\x82\x01\n\x12SubscribeSignedVAA\x12!.spy.v1.SubscribeSignedVAARequest\x1a".spy.v1.SubscribeSignedVAAResponse"#\x82\xd3\xe4\x93\x02\x1d"\x18/v1:subscribe_signed_vaa:\x01*0\x01\x12\x9c\x01\n\x18SubscribeSignedVAAByType\x12\'.spy.v1.SubscribeSignedVAAByTypeRequest\x1a(.spy.v1.SubscribeSignedVAAByTypeResponse"+\x82\xd3\xe4\x93\x02%" /v1:subscribe_signed_vaa_by_type:\x01*0\x01\x42;Z9github.com/certusone/wormhole/node/pkg/proto/spy/v1;spyv1b\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "spy.v1.spy_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"Z9github.com/certusone/wormhole/node/pkg/proto/spy/v1;spyv1"
    )
    _SPYRPCSERVICE.methods_by_name["SubscribeSignedVAA"]._options = None
    _SPYRPCSERVICE.methods_by_name[
        "SubscribeSignedVAA"
    ]._serialized_options = (
        b'\202\323\344\223\002\035"\030/v1:subscribe_signed_vaa:\001*'
    )
    _SPYRPCSERVICE.methods_by_name["SubscribeSignedVAAByType"]._options = None
    _SPYRPCSERVICE.methods_by_name[
        "SubscribeSignedVAAByType"
    ]._serialized_options = (
        b'\202\323\344\223\002%" /v1:subscribe_signed_vaa_by_type:\001*'
    )
    _EMITTERFILTER._serialized_start = 112
    _EMITTERFILTER._serialized_end = 193
    _BATCHFILTER._serialized_start = 195
    _BATCHFILTER._serialized_end = 279
    _BATCHTRANSACTIONFILTER._serialized_start = 281
    _BATCHTRANSACTIONFILTER._serialized_end = 361
    _FILTERENTRY._serialized_start = 364
    _FILTERENTRY._serialized_end = 549
    _SUBSCRIBESIGNEDVAAREQUEST._serialized_start = 551
    _SUBSCRIBESIGNEDVAAREQUEST._serialized_end = 616
    _SUBSCRIBESIGNEDVAABYTYPEREQUEST._serialized_start = 618
    _SUBSCRIBESIGNEDVAABYTYPEREQUEST._serialized_end = 689
    _SUBSCRIBESIGNEDVAARESPONSE._serialized_start = 691
    _SUBSCRIBESIGNEDVAARESPONSE._serialized_end = 738
    _SUBSCRIBESIGNEDVAABYTYPERESPONSE._serialized_start = 741
    _SUBSCRIBESIGNEDVAABYTYPERESPONSE._serialized_end = 906
    _SPYRPCSERVICE._serialized_start = 909
    _SPYRPCSERVICE._serialized_end = 1216
# @@protoc_insertion_point(module_scope)
