"""adds mints table

Revision ID: 0003
Revises: 0002
Create Date: 2023-09-06 13:12:03.865881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mints",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("chain_tx_id", sa.BigInteger(), nullable=True),
        sa.Column("account", sa.String(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["chain_tx_id"],
            ["ax_scan.evm_transactions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chain_tx_id"),
        schema="ax_scan",
    )
    op.create_index(
        op.f("ix_ax_scan_mints_account"),
        "mints",
        ["account"],
        unique=False,
        schema="ax_scan",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ax_scan_mints_account"), table_name="mints", schema="ax_scan"
    )
    op.drop_table("mints", schema="ax_scan")
    # ### end Alembic commands ###
