"""adds points table

Revision ID: 0004
Revises: 0003
Create Date: 2023-09-06 14:26:25.622201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('points',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account', sa.String(), nullable=False),
    sa.Column('points', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ax_scan'
    )
    op.create_index(op.f('ix_ax_scan_points_account'), 'points', ['account'], unique=True, schema='ax_scan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ax_scan_points_account'), table_name='points', schema='ax_scan')
    op.drop_table('points', schema='ax_scan')
    # ### end Alembic commands ###