"""fixes block records

Revision ID: 0005
Revises: 0004
Create Date: 2023-09-19 00:45:03.457658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('block_record', 'task_id',
               existing_type=sa.BIGINT(),
               nullable=False,
               schema='ax_scan')
    op.drop_constraint('block_record_chain_id_key', 'block_record', schema='ax_scan', type_='unique')
    op.create_index('ix_task_id_chain_id', 'block_record', ['task_id', 'chain_id'], unique=True, schema='ax_scan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_id_chain_id', table_name='block_record', schema='ax_scan')
    op.create_unique_constraint('block_record_chain_id_key', 'block_record', ['chain_id'], schema='ax_scan')
    op.alter_column('block_record', 'task_id',
               existing_type=sa.BIGINT(),
               nullable=True,
               schema='ax_scan')
    # ### end Alembic commands ###