"""Makes transaction_id unique in relays

Revision ID: 0002
Revises: 0001
Create Date: 2023-06-06 19:24:31.199184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relays_transaction_id', table_name='relays')
    op.create_index(op.f('ix_relays_transaction_id'), 'relays', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relays_transaction_id'), table_name='relays')
    op.create_index('ix_relays_transaction_id', 'relays', ['transaction_id'], unique=False)
    # ### end Alembic commands ###