"""Added non null constraint on transaction_id in relays

Revision ID: 0003
Revises: 0002
Create Date: 2023-06-07 15:33:57.980639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relays', 'transaction_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('relays', 'transaction_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###