version: "3.8"

services:
  # ****************************************************************************
  #
  #  Main Containers
  #
  # ****************************************************************************
  ax_scan:
    build:
      dockerfile: Dockerfile
    ports:
      - "11000:11000"
    container_name: ax_scan
    env_file:
      - .env
