name: spy_listener_ci

on:
  push:
    branches:
      - main
    paths:
      - "wormhole/spy_listener/**"
  pull_request:
    paths:
      - "wormhole/spy_listener/**"

env:
  # DB
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
  POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  DB_URL: "postgresql://user:password@localhost/example"
  DB_SCHEMA: "ax_relayer"

  # Unique Set
  REDIS_ZSET: ${{ secrets.REDIS_ZSET }}
  REDIS_URL: ${{ secrets.REDIS_URL }}
  # Wormhole
  GUARDIAN_SPY_URL: "https://spy.example.com"
  SPY_SERVICE_FILTERS: "example"
  CHAIN_LOOKUP: "example"
  # Addresses
  RELAYER_PRIVATE_KEY: "0x"
  RELAYER_ADDRESS: "0x"
  WORMHOLE_BRIDGE_ABI: "example"
  RECONNECT_WAIT_TIME: 2

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r wormhole/spy_listener/requirements.txt

      - name: Create containers
        id: create-containers
        run: |
          docker run -d \
          --name test_ax_database \
          --env POSTGRES_HOST=db \
          --env POSTGRES_PORT=5444 \
          --env POSTGRES_USER=postgres \
          --env POSTGRES_PASSWORD=postgres \
          --env POSTGRES_DB=ax_services_dev_test \
          -p 5444:5444 \
          library/postgres:12-alpine -p 5444

      - name: Database setup
        id: database-setup
        run: |
          python ci/initialize_database.py
          cd wormhole/spy_listener
          alembic upgrade head

      - name: Lint apps
        id: lint
        run: |
          cd wormhole/spy_listener
          make lint
        continue-on-error: false

      - name: Format check
        id: format_check
        run: |
          cd wormhole/spy_listener
          make format-check
        continue-on-error: false

      - name: Run tests
        id: tests
        run: |
          cd wormhole/spy_listener
          make test
        continue-on-error: false
